# Generated by Django 4.1 on 2023-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_text',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
