# Generated by Django 4.1 on 2023-02-09 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_product_detailed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
